#!/bin/bash
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/bio.c ~/dwtlift-pi/encode_decode/src/bio.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/bio.h ~/dwtlift-pi/encode_decode/src/bio.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/cio.c ~/dwtlift-pi/encode_decode/src/cio.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/cio.h ~/dwtlift-pi/encode_decode/src/cio.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/dwt.c ~/dwtlift-pi/encode_decode/src/dwt.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/dwt.h ~/dwtlift-pi/encode_decode/src/dwt.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/dwtlift.c ~/dwtlift-pi/encode_decode/src/dwtlift.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/dwtlift.h ~/dwtlift-pi/encode_decode/src/dwtlift.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/event.c ~/dwtlift-pi/encode_decode/src/event.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/event.h ~/dwtlift-pi/encode_decode/src/event.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/format_defs.h ~/dwtlift-pi/encode_decode/src/format_defs.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/function_list.h ~/dwtlift-pi/encode_decode/src/function_list.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/function_list.c ~/dwtlift-pi/encode_decode/src/function_list.c 
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/image.h ~/dwtlift-pi/encode_decode/src/image.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/image.c ~/dwtlift-pi/encode_decode/src/image.c 
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/invert.c ~/dwtlift-pi/encode_decode/src/invert.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/invert.h ~/dwtlift-pi/encode_decode/src/invert.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/j2k.c ~/dwtlift-pi/encode_decode/src/j2k.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/j2k.h ~/dwtlift-pi/encode_decode/src/j2k.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/jp2.c ~/dwtlift-pi/encode_decode/src/jp2.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/jp2.h ~/dwtlift-pi/encode_decode/src/jp2.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/mct.c ~/dwtlift-pi/encode_decode/src/mct.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/mct.h ~/dwtlift-pi/encode_decode/src/mct.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/mqc.c ~/dwtlift-pi/encode_decode/src/mqc.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/mqc.h ~/dwtlift-pi/encode_decode/src/mqc.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/mqc_inl.h ~/dwtlift-pi/encode_decode/src/mqc_inl.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/openjpeg.c ~/dwtlift-pi/encode_decode/src/openjpeg.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/openjpeg.h ~/dwtlift-pi/encode_decode/src/openjpeg.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/opj_clock.c ~/dwtlift-pi/encode_decode/src/opj_clock.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/opj_clock.h ~/dwtlift-pi/encode_decode/src/opj_clock.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/opj_codec.h ~/dwtlift-pi/encode_decode/src/opj_codec.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/opj_common.h ~/dwtlift-pi/encode_decode/src/opj_common.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/opj_config.h ~/dwtlift-pi/encode_decode/src/opj_config.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/opj_config_private.h ~/dwtlift-pi/encode_decode/src/opj_config_private.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/opj_includes.h ~/dwtlift-pi/encode_decode/src/opj_includes.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/opj_intmath.h ~/dwtlift-pi/encode_decode/src/opj_intmath.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/opj_inttypes.h ~/dwtlift-pi/encode_decode/src/opj_inttypes.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/opj_malloc.c ~/dwtlift-pi/encode_decode/src/opj_malloc.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/pi.h ~/dwtlift-pi/encode_decode/src/pi.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/pi.c ~/dwtlift-pi/encode_decode/src/pi.c 
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/opj_stdint.h ~/dwtlift-pi/encode_decode/src/opj_stdint.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/raw.h ~/dwtlift-pi/encode_decode/src/raw.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/rdwr.h ~/dwtlift-pi/encode_decode/src/rdwr.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/rd-wr-ops.c ~/dwtlift-pi/encode_decode/src/rd-wr-ops.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/t1.h ~/dwtlift-pi/encode_decode/src/t1.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/t1.c ~/dwtlift-pi/encode_decode/src/t1.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/t1_luts.h ~/dwtlift-pi/encode_decode/src/t1_luts.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/t2.h ~/dwtlift-pi/encode_decode/src/t2.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/t2.c ~/dwtlift-pi/encode_decode/src/t2.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/tcd.h ~/dwtlift-pi/encode_decode/src/tcd.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/tcd.c ~/dwtlift-pi/encode_decode/src/tcd.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/tgt.h ~/dwtlift-pi/encode_decode/src/tgt.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/tgt.c ~/dwtlift-pi/encode_decode/src/tgt.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/thread.h ~/dwtlift-pi/encode_decode/src/thread.h
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/thread.c ~/dwtlift-pi/encode_decode/src/thread.c
diff ~/test-openjpeg-ultibo-b07d/openjpeg/src/lib/openjp2/tls_keys.h ~/dwtlift-pi/encode_decode/src/tls_keys.h
diff encode_decode.h ~/dwtlift-pi/encode_decode/encode_decode.h
